### ISSUE TITLE
cannot define --separator option

### ISSUE THREAD

**Issue by weitzj** [apauley/hledger-flow#67]
**Is your feature request related to a problem? Please describe.**

I would like to import CSV files, which use `;` as a separatorchar

**Version and Runtime Information**

Please mention the version number of `hledger-flow` you are using:
```
$ hledger-flow --version
hledger-flow 0.12.3.0 linux x86_64 ghc 8.6
```

Is this the [latest version](https://github.com/apauley/hledger-flow/releases)?

If your request includes commands you ran and the output, please also include
the runtime options with `--show-options` e.g:

```
$ hledger-flow --show-options import
 hledger-flow --show-options import
RuntimeOptions {baseDir = FilePath "/data/", hfVersion = "hledger-flow 0.12.3.0 linux x86_64 ghc 8.6", hledgerInfo = HledgerInfo {hlPath = FilePath "/usr/bin/hledger", hlVersion = "hledger 1.14.2"}, sysInfo = SystemInfo {os = "linux", arch = "x86_64", compilerName = "ghc", compilerVersion = Version {versionBranch = [8,6], versionTags = []}}, verbose = False, showOptions = True, sequential = False}
```

**Our Example Statements Repository**

https://gist.github.com/weitzj/228ea40f4db33bfe2f49d2d7e43a2871

Can you give examples of what you would like by running `hledger-flow` on these files?

I would like to have the same behaviour as:

`hledger import --separator=";" --file=....`

Even better would be that hledger-flow delegates all options to `hledger import`

**Describe alternatives you've considered**

Using `hledger import --separator=";" ` and giving up on hledger-flow

**Comment by apauley** [comment]
Hi @weitzj, thanks for taking the time to write up this request.

We've previously discussed this exact issue:
https://github.com/apauley/hledger-flow/issues/49#issuecomment-491050880

To summarize:
 - `hledger-flow` can help you here, just in a different way than you requested.
 - We don't want to add any separator option to the command-line options of `hledger-flow`, because `hledger-flow` operates on multiple accounts and we don't want to enforce something intended for one account on all accounts.
 - The proper solution for this issue would be to add a separator option in hledger's rules file itself. You should help flesh out some of the design issues in this hledger issue: https://github.com/simonmichael/hledger/issues/868
 - Right now `hledger-flow` can help you if you use a `preprocess` or a `construct` script.
 - The `construct` script could possibly be an easy solution, the contents of such a script could just be an hledger import for the relevant account with any options you need, e.g. `--separator=";"`
 - If you go for the `preprocess` script option then that would change the separator of the input files.

Hope that helps you move forward with automating your finances!

**Comment by weitzj** [comment]
Hi @apauley . Thanks for the heads-up. I did not see the other issue. Shame on me. I like the idea of the separator-char option in the rules file. That would be superb.
